export const weatherDescriptions: any = {
  'thunderstorm with light rain': 'Tormenta con lluvia ligera',
  'thunderstorm with rain': 'Tormenta con lluvia',
  'thunderstorm with heavy rain': 'Tormenta con lluvia fuerte',
  'light thunderstorm': 'Tormenta ligera',
  thunderstorm: 'Tormenta',
  'heavy thunderstorm': 'Tormenta fuerte',
  'ragged thunderstorm': 'Tormenta irregular',
  'thunderstorm with light drizzle': 'Tormenta con llovizna ligera',
  'thunderstorm with drizzle': 'Tormenta con llovizna',
  'thunderstorm with heavy drizzle': 'Tormenta con llovizna fuerte',
  'light intensity drizzle': 'Llovizna de intensidad ligera',
  drizzle: 'Llovizna',
  'heavy intensity drizzle': 'Llovizna de intensidad fuerte',
  'light intensity drizzle rain': 'Llovizna con lluvia de intensidad ligera',
  'drizzle rain': 'Lluvia con llovizna',
  'heavy intensity drizzle rain': 'Llovizna con lluvia de intensidad fuerte',
  'shower rain and drizzle': 'Chubasco y llovizna',
  'heavy shower rain and drizzle': 'Chubasco fuerte y llovizna',
  'shower drizzle': 'Chubasco con llovizna',
  'light rain': 'Lluvia ligera',
  'moderate rain': 'Lluvia moderada',
  'heavy intensity rain': 'Lluvia de intensidad fuerte',
  'very heavy rain': 'Lluvia muy fuerte',
  'extreme rain': 'Lluvia extrema',
  'freezing rain': 'Lluvia helada',
  'light intensity shower rain': 'Chubasco de intensidad ligera',
  'shower rain': 'Chubasco',
  'heavy intensity shower rain': 'Chubasco de intensidad fuerte',
  'ragged shower rain': 'Chubasco irregular',
  'light snow': 'Nieve ligera',
  snow: 'Nieve',
  'heavy snow': 'Nieve fuerte',
  sleet: 'Aguanieve',
  'light shower sleet': 'Chubasco de aguanieve ligera',
  'shower sleet': 'Chubasco de aguanieve',
  'light rain and snow': 'Lluvia ligera y nieve',
  'rain and snow': 'Lluvia y nieve',
  'light shower snow': 'Chubasco de nieve ligera',
  'shower snow': 'Chubasco de nieve',
  'heavy shower snow': 'Chubasco de nieve fuerte',
  mist: 'Neblina',
  smoke: 'Humo',
  haze: 'Calina',
  'sand/dust whirls': 'Remolinos de arena/polvo',
  fog: 'Niebla',
  sand: 'Arena',
  dust: 'Polvo',
  'volcanic ash': 'Ceniza volcánica',
  squalls: 'Ráfagas',
  tornado: 'Tornado',
  'clear sky': 'Cielo despejado',
  'few clouds': 'Pocas nubes',
  'scattered clouds': 'Nubes dispersas',
  'broken clouds': 'Nubes fragmentadas',
  'overcast clouds': 'Nubes cubiertas',
};
